eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8201/eureka/
server:
  port: 8600
spring:
  application:
    name: service-zuul
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign
zuul:
  routes:
    api-a:
      path: /service-customer/**
      serviceId: service-customer
    api-b:
      path: /service-order/**
      serviceId: service-order
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
