spring:
  application:
    name: user
#  security:
#    user:
#      name: "client"
#      password: "client"

eureka:
  instance:
    # 续约更新时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5

    health-check-url-path: /actuator/health

  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8750}/eureka/

      # 默认值为false。设为true，开启健康检查（需要spring-boot-starter-actuator 依赖）
    healthcheck:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8753