spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.sina.com
    username: luxing3@sina.com
    password: luo770524
#    protocol: smtp
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#          starttls:
#            enable: true
#            required: true
#  spring.mail.protocol=smtp
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.ssl.enable=true
#  spring.mail.test-connection=true
  boot:
    admin:
      notify:
        mail:
          from: luxing3@sina.com
          to: luxing@irongwei.com
server:
  port: 8751
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8750}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS




